# Generated by Django 4.2.20 on 2025-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_image', models.CharField(max_length=255, verbose_name='Исходное фото')),
                ('result_image', models.CharField(max_length=255, verbose_name='Аннотированное фото')),
                ('pdf_report', models.CharField(max_length=255, verbose_name='PDF-отчёт')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во посетителей')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
